version: '3.9'
services:
  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    volumes:
      - ./postgres-volume:/var/lib/postgresql/volumes
    healthcheck:
      test: "pg_isready -d ${POSTGRESQL_DB} -U ${POSTGRESQL_USER}"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - billing-system-network
    restart: always

  config-server:
    build:
      context: ConfigServer
      dockerfile: Dockerfile
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    env_file:
      - .env
    networks:
      - billing-system-network
    restart: always

  data-gen:
    build:
      context: DataGen
      dockerfile: Dockerfile
    ports:
      - "${DATA_GEN_PORT}:${DATA_GEN_PORT}"
    env_file:
      - .env
    networks:
      - billing-system-network
    restart: always
    volumes:
      - ./files:/home/files

networks:
  billing-system-network:
    driver: bridge
