crm-service:
  port: ${CRM_PORT:8080}
  servlet-context-path: /crm

  destination-queue:
    tariffication: tariffication-mq

  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000  # Сутки

  security-enabled: true
