data-gen-service:
  port: ${DATA_GEN_PORT:8081}
  servlet-context-path: /data-gen

  services:
    call-type-generator:
      incoming-call-chance: 0.5
      incoming-call-code: "01"
      outcoming-call-code: "02"
