name: TRKPO GH Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '15'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: postgres

      - name: Checkout Backend project
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Run build
        run: mvn clean install -DskipTests

      - name: Run Unit Tests
        run: mvn test -DskipIntegrationTests

      - name: Run Integration Tests
        run: mvn test -DskipUnitTests
